name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Kết nối ssh linux -> và pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINUX_HOST }}
        username: ${{ secrets.LINUX_USERNAME }}
        password: ${{ secrets.LINUX_PASSWORD }}
        port: 22
        script: |
          echo "--------Truy cập vào thư mục dự án"
          cd /var/www/phoneshop/phoneshop_server

          echo "--------Pull code mới từ github"
          git pull       
          git status

          echo "--------kích hoạt kiểm tra nvm"
          . $HOME/.nvm/nvm.sh
          nvm use

          echo "--------Tạo .env và chỉnh sửa"
          cp .env.example .env
          sed -i 's/DB_USER/${{ secrets.DB_USER }}/g' .env
          sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' .env
          sed -i 's/DB_HOST/${{ secrets.LINUX_HOST }}/g' .env
          sed -i 's/DB_PORT/${{ secrets.DB_PORT }}/g' .env
          sed -i 's/DB_NAME/${{ secrets.DB_NAME }}/g' .env

          sed -i 's/API_HOST/${{ secrets.API_HOST }}/g' .env
          sed -i 's/MAILER_ACC/${{ secrets.MAILER_ACC }}/g' .env
          sed -i 's/MAILER_PASS/${{ secrets.MAILER_PASS }}/g' .env
          sed -i 's/HASH_KEY/${{ secrets.HASH_KEY }}/g' .env
          sed -i 's/BOTTOKEN/${{ secrets.BOTTOKEN }}/g' .env
          sed -i 's/DISCORD_CHANNEL_ID/${{ secrets.DISCORD_CHANNEL_ID }}/g' .env
          
          echo "--------Cài đặt package theo package.json"
          npm ci

          echo "--------tạo prisma client cho node modules"
          npx prisma generate

          echo "--------Build dự án"
          npm run build

          echo "--------Reset Bộ Nhớ Swap"
          sudo swapoff -a; sudo swapon -a

          echo "--------Gửi thông báo!"
          echo "curl -X POST -H "Content-Type: application/json" -H "Authorization:${{ secrets.DISCORD_TOKEN }}" -d '{"content":"Dự án node js đã deploy thành công link: https://api.khangdev.io.vn/ "}' ${{ secrets.DISCORD_URL }}"
